      # Sign the Phone APK
        name: Sign Phone APK
        uses: r0adkll/sign-android-release@v1
        id: sign_phone
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: "34.0.0" # Added to find zipalign correctly

      # Sign the Watch APK
      - name: Sign Watch APK
        uses: r0adkll/sign-android-release@v1
        id: sign_watch
        with:
          releaseDirectory: wear/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: "34.0.0" # Added to find zipalign correctly
